name: Publish
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade ansible
    - name: Report Ansible version
      run: ansible --version
    - name: Get the version from the tag
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//
    - name: Deploy Ansible Galaxy Collection
      uses: artis3n/ansible_galaxy_collection@v2
      with:
        api_key: ${{ secrets.GALAXY_API_KEY }}
        collection_dir: ansible_collections/ctera/ctera
        galaxy_version: '${{ env.RELEASE_VERSION }}'
